AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: FastAPI + Mangum Lambda

Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    MemorySize: 512

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.main.handler
      CodeUri: .
      Runtime: python3.11
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          DYNAMODB_ENDPOINT_URL: !Ref DynamoDbEndpointUrl
          AWS_REGION: ap-northeast-1

Parameters:
  DynamoDbEndpointUrl:
    Type: String
    Default: https://dynamodb.ap-northeast-1.amazonaws.com
